Merge state level with main
USEPA/FrEDI pull request #146
Opened 2024-02-16 18:16 UTC by knoiva-indecon

This branch was created to do a precursor merge between the main and state_level branches. Request any changes here and we'll update this branch until you are ready to approve the pull request

2024-02-20 18:25 UTC, emcduffie requested changes
Looks great. I had a few comments/questions throughout. If you could respond to these, then I can approve the merge. Thanks!

2024-02-20 18:25 UTC, emcduffie commented on FrEDI/DESCRIPTION
> +    above calculate values at the state-level for most sectors.
So we don't for get to update this, let's just say '4.0 and above calculate values at the state-level.'

2024-02-20 18:25 UTC, emcduffie commented on FrEDI/DESCRIPTION
> +Version: 4.0
Can we change to '4.0-public-review'?

2024-02-20 18:25 UTC, emcduffie commented on FrEDI/R/configTests.R
>    ### GDP Plot: Convert to Billions
Change: "GDP Plot: Convert to 'Trillions"

2024-02-20 18:25 UTC, emcduffie commented on FrEDI/R/configTests.R
>    ### Pop plot
Change: "Population Plot: Convert to Millions"

2024-02-20 18:25 UTC, emcduffie commented on FrEDI/R/data.R
> +# Default outputs of [FrEDI::run_fredi()]
Is this description still accurate? Or is there state-level column information that needs to be added here?

2024-02-20 18:25 UTC, emcduffie commented on FrEDI/R/import_inputs.R
> +#' @param popfile A character string indicating the location of a CSV file containing a custom population scenario for states and NCA regions. The first column contains years in the interval 2010 to
DO we currently have the option for users to specify national or regional totals and then FrEDI will calculate the state-proportions based on the default ICLUS data? If not, let's add this to the list to discuss as a future update after we finish v4.0.

2024-02-20 18:25 UTC, emcduffie commented on FrEDI/R/import_inputs.R
> +# #' If the population input is spread across multiple columns (i.e., `popform="wide"`), columns must be named according to the NCA regions. If the population input is in the long format, the region
Confirm - does the new state format allow input population data to either be in wide form or long form? Therefore, is this note still relevant?

2024-02-20 18:25 UTC, emcduffie commented on FrEDI/R/run_fredi.R
> +#' As of FrEDI Version 4.0, [FrEDI::run_fredi()] calculates impacts at the state-level for the following sectors: **ATS Temperature-Related Mortality**, **Asphalt Roads**, **Climate-Driven Changes in
As of FrEDI Version 4.0-public-comment,

2024-02-22 22:18 UTC, knoiva-indecon commented on FrEDI/DESCRIPTION
> +    above calculate values at the state-level for most sectors.
Changed!

2024-02-22 22:19 UTC, knoiva-indecon commented on FrEDI/DESCRIPTION
> +Version: 4.0
Not quite...R doesn't like having characters in the version number. I changed it to 4.0.1.

2024-02-22 22:19 UTC, knoiva-indecon commented on FrEDI/R/configTests.R
>    ### GDP Plot: Convert to Billions
Changed

2024-02-22 22:19 UTC, knoiva-indecon commented on FrEDI/R/configTests.R
>    ### Pop plot
Changed. Also edited plot since the plot code was expecting region-level data.

2024-02-22 22:20 UTC, knoiva-indecon commented on FrEDI/R/data.R
> +# Default outputs of [FrEDI::run_fredi()]
I modified the description to reflect recent changes

2024-02-22 22:28 UTC, knoiva-indecon commented on FrEDI/R/import_inputs.R
> +#' @param popfile A character string indicating the location of a CSV file containing a custom population scenario for states and NCA regions. The first column contains years in the interval 2010 to
No we don't...I opened Issue #152 so we have it for the future.

2024-02-22 22:29 UTC, knoiva-indecon commented on FrEDI/R/run_fredi.R
> +#' As of FrEDI Version 4.0, [FrEDI::run_fredi()] calculates impacts at the state-level for the following sectors: **ATS Temperature-Related Mortality**, **Asphalt Roads**, **Climate-Driven Changes in
I think it's fine to leave it as Version 4.0, but I changed it to 4.0.1 (public comment)

2024-02-22 22:30 UTC, knoiva-indecon commented
@emcduffie : I made changes to the documentation as specified. Please check the changes and make sure they look fine.

2024-02-22 22:42 UTC, knoiva-indecon commented
@emcduffie: Responded to requested changes. Let me know if additional changes required.

2024-02-22 22:52 UTC, emcduffie approved these changes

2024-02-22 22:52 UTC, merged