Pop downscaling
USEPA/FrEDI pull request #172
Opened 2024-07-02 22:11 UTC by knoiva-indecon

Merging in population downscaling functionality to state level

2024-07-04 20:27 UTC, emcduffie requested changes
Looks great, just a few minor suggested text edits!

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/R/FrEDI-package.R
> +#' FrEDI is an R package being developed by the U.S. Environmental Protection Agency (EPA). The functions and data provided by this package can be used to estimate climate change impacts for the cont
```suggestion
#' FrEDI is an R package that is developed and maintained by the U.S. Environmental Protection Agency (EPA). The functions and data provided in this package can be used to project impacts of climate change within the contiguous United States (CONUS), under any custom temperature or socioeconomic trajectory, using the [Framework for Evaluating Damages and Impacts (FrEDI)](https://epa.gov/cira/FrEDI/) that was developed as part of EPA's [Climate Change Impacts and Risk Analysis](https://epa.gov/cira/) (CIRA) project. The FrEDI package contains R code that implements FrEDI and allows users to project annual impacts from climate change and sea level rise across over 20 impact sectors, geographic regions, and populations through the end of the 21st century (and optionally through 2300). While this framework does not currently account for all ways in which the American public may be impacted by future climate change, this type of detailed information helps EPA to better understand and communicate the types of potential impacts and risks from future climate change in the United States, as well as the potential benefits of greenhouse gas mitigation and adaptation. 
See the [FrEDI Technical Documentation](https://epa.gov/cira/about-fredi/) for additional information about the underlying theory, design, structure, components, and capabilities of FrEDI, as well as examples of some of its intended uses and applications. 
```

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/R/FrEDI-package.R
See suggested edits for the intro section (to better align with the intro of our TD)

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/R/data.R
At line 57, change to: Population scenario to use as an input to [FrEDI::run_fredi()] and [FrEDI::run_fredi_sv()]

Line 33 and 35: The 6 GCAM scenarios can be used as drivers from both run_fredi() and run_fredi_sv(), right? If so, please update to clarify. Do we also need to specify where the default GDP scenarios are from? Or is this documented elsewhere?

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/R/import_inputs.R
> +#'    * If `popArea = "state"`, the third column should be called `"state"` and contain the name of the state associated with each population estimate in a given year. If `popArea = "regional"`, the
What does popArea = "area" mean? We have national, regional, and state, but what is 'area'? Can we clarify that here? Can we also clarify whether 'national' includes AK and HI or not. Thanks!

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/R/import_inputs.R
> +#' * If `popArea = "national"` or or `popArea = "area"`, [FrEDI::import_inputs()] uses ICLUS data and projections for the period 2010--2100 to allocate CONUS population to specific NCA regions; ICLUS
remove double 'or or'

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/R/import_inputs.R
>  #' @references Environmental Protection Agency (EPA). 2021. Technical Documentation on The Framework for Evaluating Damages and Impacts (FrEDI). Technical Report EPA 430-R-21-004, EPA, Washington, DC
Update to our latest TD: Environmental Protection Agency (EPA). 2024. Technical Documentation for the Framework for Evaluating Damages and Impacts (FrEDI). U.S. Environmental Protection Agency, EPA 430-R-24-001. [www.epa.gov/cira/FrEDI](http://www.epa.gov/cira/FrEDI)

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/R/run_fredi.R
> +#' If `inputsList = NULL`, [FrEDI::run_fredi()] uses defaults for temperature, SLR, GDP, and population. Otherwise, [FrEDI::run_fredi()] looks for a list object passed to the argument `inputsList`. W
update 'regional population' to 'state population'

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/R/run_fredi_sv.R
> +#' `run_fredi_sv` allows users to project annual average climate change impacts throughout the 21st century (2010-2100) for socially vulnerable (SV) populations for available sectors. Users can run [
```suggestion
#' `run_fredi_sv` allows users to project annual average climate change impacts throughout the 21st century (2010-2100) for socially vulnerable (SV) populations for available sectors. Users can run [FrEDI::run_fredi_sv()] for individual sectors to generate annual physical impacts for SV populations. [FrEDI::run_fredi_sv()] can be run with default population and climate (temperature and sea level rise trajectories) or using custom trajectories. The output of [FrEDI::run_fredi_sv()] is an R data frame object containing annual average physical impacts at five-year increments for the period 2010 to 2100. The basic structure, specific methodology, and underlying data supporting FrEDI-SV are derived from EPA’s independently peer-reviewed September 2021 report, [Climate Change and Social Vulnerability in the United States: A Focus on Six Impacts](https://epa.gov/cira/social-vulnerability-report)
```

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/R/utils_import_inputs.R
> -### Created 2021.02.08. Last updated 2021.02.08
Up to you whether you want to keep these 'Last Updated' dates throughout all the code in the R package. If so, I would recommend going through and updating the relevant dates before merging.

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/testing/utils_create_report_figures.R
>      years0   = c(2010, 2090),
plot through 2100?

2024-07-04 20:27 UTC, emcduffie commented on FrEDI/testing/utils_create_report_figures.R
> +  years0     <- c(2010, 2090)
plot 2100 results instead of 2090?

2024-07-04 20:35 UTC, knoiva-indecon commented
Awesome, thanks for the review! I’ll make those edits later today or tomorrow.
________________________________
From: Erin McDuffie ***@***.***>
Sent: Thursday, July 4, 2024 4:27:50 PM
To: USEPA/FrEDI ***@***.***>
Cc: Karen Noiva ***@***.***>; Author ***@***.***>
Subject: Re: [USEPA/FrEDI] Pop downscaling (PR #172)


Note: This email originated outside of IEc. Be cautious with any links or attachments.

@emcduffie requested changes on this pull request.

Looks great, just a few minor suggested text edits!

________________________________

In FrEDI/R/FrEDI-package.R<https://github.com/USEPA/FrEDI/pull/172#discussion_r1666019850>:

>  #'
-#' For help getting started with [FrEDI], visit <https://usepa.github.io/FrEDI/articles/manual.html>.
+#' FrEDI is an R package being developed by the U.S. Environmental Protection Agency (EPA). The functions and data provided by this package can be used to estimate climate change impacts for the contiguous United States (CONUS) using the [Framework for Evaluating Damages and Impacts (FrEDI)](https://epa.gov/cira/FrEDI/), developed as part of EPA's [Climate Change Impacts and Risk Analysis](https://epa.gov/cira/) (CIRA) project. FrEDI contains R code that implement FrEDI and allow users to project impacts from climate change and sea level rise for a selected set of sectors.


⬇️ Suggested change

-#' FrEDI is an R package being developed by the U.S. Environmental Protection Agency (EPA). The functions and data provided by this package can be used to estimate climate change impacts for the contiguous United States (CONUS) using the [Framework for Evaluating Damages and Impacts (FrEDI)](https://epa.gov/cira/FrEDI/), developed as part of EPA's [Climate Change Impacts and Risk Analysis](https://epa.gov/cira/) (CIRA) project. FrEDI contains R code that implement FrEDI and allow users to project impacts from climate change and sea level rise for a selected set of sectors.
+#' FrEDI is an R package that is developed and maintained by the U.S. Environmental Protection Agency (EPA). The functions and data provided in this package can be used to project impacts of climate change within the contiguous United States (CONUS), under any custom temperature or socioeconomic trajectory, using the [Framework for Evaluating Damages and Impacts (FrEDI)](https://epa.gov/cira/FrEDI/) that was developed as part of EPA's [Climate Change Impacts and Risk Analysis](https://epa.gov/cira/) (CIRA) project. The FrEDI package contains R code that implements FrEDI and allows users to project annual impacts from climate change and sea level rise across over 20 impact sectors, geographic regions, and populations through the end of the 21st century (and optionally through 2300). While this framework does not currently account for all ways in which the American public may be impacted by future climate change, this type of detailed information helps EPA to better understand and communicate the types of potential impacts and risks from future climate change in the United States, as well as the potential benefits of greenhouse gas mitigation and adaptation.
+See the [FrEDI Technical Documentation](https://epa.gov/cira/about-fredi/) for additional information about the underlying theory, design, structure, components, and capabilities of FrEDI, as well as examples of some of its intended uses and applications.


________________________________

On FrEDI/R/FrEDI-package.R<https://github.com/USEPA/FrEDI/pull/172#discussion_r1666023217>:

See suggested edits for the intro section (to better align with the intro of our TD)

________________________________

On FrEDI/R/data.R<https://github.com/USEPA/FrEDI/pull/172#discussion_r1666025433>:

At line 57, change to: Population scenario to use as an input to [FrEDI::run_fredi()] and [FrEDI::run_fredi_sv()]

Line 33 and 35: The 6 GCAM scenarios can be used as drivers from both run_fredi() and run_fredi_sv(), right? If so, please update to clarify. Do we also need to specify where the default GDP scenarios are from? Or is this documented elsewhere?

________________________________

In FrEDI/R/import_inputs.R<https://github.com/USEPA/FrEDI/pull/172#discussion_r1666030362>:

>  #'
+#' * __Temperature Scenario.__ The file specified by `tempfile` must have two columns -- `"year"` and `"temp_C"` -- respectively containing the years associated with the temperature estimates and the temperatures (i.e., degrees of warming) in degrees Celsius relative to a baseline year of 1995 (i.e., the central year of a 1986-2005 reference period).
+#'    * If expressed as CONUS temperatures, values in the `"temp_C"` column must be greater than or equal to zero degrees Celsius.
+#'    * If values in `"temp_C"` have global rather than CONUS-specific temperatures, users should specify `temptype = "global"` when running `import_inputs()`, and `import_inputs()` will convert the temperatures to CONUS using [FrEDI::convertTemps] (with argument `from = "global"`).
+#'    * Temperature inputs to [FrEDI::run_fredi()] must have at least one non-missing value in 2000 or earlier and at least one non-missing value in or after the final analysis year (as specified by the [FrEDI::run_fredi()] `maxYear` argument).
+#' * __SLR Scenario.__ The file specified by `slrfile` must have two columns -- `"year"` and `"slr_cm"` -- respectively containing the years associated with the GMSL estimates and GMSL estimates, in centimeters, above a 2000 baseline year.
+#'    * GMSL heights must be greater than or equal to zero.
+#'    * The SLR scenario must have at least one non-missing value in 2000 or earlier and at least one non-missing value in or after the final analysis year (as specified by the [FrEDI::run_fredi()] `maxYear` argument).
+#' * __GDP Scenario.__ The file specified by `gdpfile` must have two columns -- `"year"` and `"gdp_usd"` -- respectively containing the years associated with the GDP estimates and the estimates for U.S. GDP, in 2015$.
+#'    * GDP values must be greater than or equal to zero.
+#'    * The GDP scenario must have at least one non-missing value in 2010 or earlier and at least one non-missing value in or after the final analysis year (as specified by the [FrEDI::run_fredi()] `maxYear` argument).
+#' * __Population Scenario.__ The file specified by `popfile` population must have at least two columns -- `"year"` and `"pop"` -- respectively containing the years associated with the population estimates and the population estimates. requires state-level population values. Whether a third column is required depends on the geographical scale of the data, as specified by the `popArea` argument.
+#'    * If `popArea = "state"`, the third column should be called `"state"` and contain the name of the state associated with each population estimate in a given year. If `popArea = "regional"`, the third column should be called `"region"` and contain the NCA Region label associated with each population estimate in a given year. If `popArea = "national"` or `popArea = "area"`, only the `year` and `pop` columns are required.


What does popArea = "area" mean? We have national, regional, and state, but what is 'area'? Can we clarify that here? Can we also clarify whether 'national' includes AK and HI or not. Thanks!

________________________________

In FrEDI/R/import_inputs.R<https://github.com/USEPA/FrEDI/pull/172#discussion_r1666030562>:

>  #'
+#' * If `popArea = "national"`, [FrEDI::import_inputs()] will use historical U.S. Census data for the period 2010--2023 to allocate total national population to CONUS and non-CONUS regions (i.e., Alaska and Hawaii); U.S. Census values from 2023 are applied in allocations for years after 2023.
+#' * If `popArea = "national"` or or `popArea = "area"`, [FrEDI::import_inputs()] uses ICLUS data and projections for the period 2010--2100 to allocate CONUS population to specific NCA regions; ICLUS values from 2100 are applied in allocations for years after 2100.


remove double 'or or'

____________________________ [...]

2024-07-08 18:06 UTC, knoiva-indecon commented on FrEDI/R/FrEDI-package.R
> +#' FrEDI is an R package being developed by the U.S. Environmental Protection Agency (EPA). The functions and data provided by this package can be used to estimate climate change impacts for the cont
Edited in merge #174

2024-07-08 18:10 UTC, knoiva-indecon commented on FrEDI/R/import_inputs.R
> +#'    * If `popArea = "state"`, the third column should be called `"state"` and contain the name of the state associated with each population estimate in a given year. If `popArea = "regional"`, the
Removed option `popArea="area"` from options in merge #174. Basically, it was an option if the user happened to have CONUS populations and estimates for Alaska and Hawaii. The function is still set up to handle `popArea="area"`, but it seems like a confusing option for a casual user, and it seems like users would be less likely to have inputs at that scale. Let me know if you think differently.

2024-07-08 18:11 UTC, knoiva-indecon commented on FrEDI/R/data.R
Made edits to line 57 and clarified using GCAM scenarios as inputs in merge #174. Will get back to you on default GDP scenarios

2024-07-08 18:11 UTC, knoiva-indecon commented on FrEDI/R/import_inputs.R
> +#' * If `popArea = "national"` or or `popArea = "area"`, [FrEDI::import_inputs()] uses ICLUS data and projections for the period 2010--2100 to allocate CONUS population to specific NCA regions; ICLUS
Fixed in merge #174

2024-07-08 18:11 UTC, knoiva-indecon commented on FrEDI/R/run_fredi.R
> +#' If `inputsList = NULL`, [FrEDI::run_fredi()] uses defaults for temperature, SLR, GDP, and population. Otherwise, [FrEDI::run_fredi()] looks for a list object passed to the argument `inputsList`. W
in merge #175

2024-07-08 18:11 UTC, knoiva-indecon commented on FrEDI/R/utils_import_inputs.R
> -### Created 2021.02.08. Last updated 2021.02.08
Removed from files in merge #175

2024-07-08 18:12 UTC, knoiva-indecon commented on FrEDI/testing/utils_create_report_figures.R
> +  years0     <- c(2010, 2090)
This is for impact years, and we have impact year estimates for 2090, so didn't change

2024-07-08 18:12 UTC, knoiva-indecon commented on FrEDI/testing/utils_create_report_figures.R
>      years0   = c(2010, 2090),
This is for impact years, and we have impact year estimates for 2090, so didn't change

2024-07-08 18:19 UTC, knoiva-indecon commented on FrEDI/R/data.R
We don't currently have a loadable GDP scenario so haven't documented it in the package. It is documented in the technical documentation (section 2.4, footnote):

> [1]In the absence of custom scenarios, FrEDI applies default population and GDP projections that are consistent with the CIRA project’s scenarios (see EPA (2017) for more details),  which align with the scenarios used in many of the underlying sectoral impact studies. The default population scenario is based on the national-level UN Median Population projection (United Nations, Department of Economic and Social Affairs, Population Division, 2015), disaggregated to the county-level using EPA’s ICLUSv2 model (Bierwagen et al., 2010; EPA, 2017b) and reaggregated to NCA regions for this analysis. GDP projection is defined by the EPPA, version 6 model (Chen et al., 2015), using the aforementioned UN Median population projection for the U.S. (United Nations, Department of Economic and Social Affairs, Population Division, 2015) and the 2016 Annual Energy Outlook reference case (USEIA, 2016) for the U.S. through 2040. The FrEDI 2300 module does not include default GDP or population projections from 2101 to 2300, and instead requires user-input for population and GDP through the year 2300 for the module to be run.

2024-07-09 18:07 UTC, knoiva-indecon commented
@emcduffie : Merge #176 tries to meet your offline request to add some flexibility to input column names:

Added flexibility to column names: Now, if the driver column is not found, the import_inputs helper function will try to string match the input type against column names. If it finds a match: 

> - If a temperature input, it will look for matches to strings "conus" and "global". If conus matches, it will use that column and set tempType to "conus". Else if global matches, it will use that column and set tempType to "global". Otherwise, it will use the first matched column. 
> - If a population input, it will look for matches to strings "state", "region", "conus", and "global". It will check for a match and use the first associated column, and set popArea accordingly. E.g., if "reg_pop" is present, but "state_pop" isn't, "reg_pop" will be used and the popArea set to "regional".
> - Otherwise, the first matched column will be used as the value column.

The function will then rename the matched column to the expected column. No flexibility enhancements were made for ID columns.

2024-07-10 00:01 UTC, emcduffie approved these changes
Thanks for addressing the changes. Please go ahead with merging into main.

2024-07-10 14:38 UTC, merged