Example FrEDI Rmd
USEPA/FrEDI pull request #59
Opened 2023-03-15 16:35 UTC by emcduffie

Adding new folder with an Example FrEDI run Rmd that formats, runs, and plots FrEDI data based on SSP emission scenarios

2023-03-16 16:48 UTC, cahartin requested changes

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +# USERS NEED TO SPECIFY THIER WORKING DIRECTORY AND PYTHON PATHS
I'm wondering if we can pull this out into 2 different Rmd or not include FaIR in this write up. Part of me wants to keep it focused and narrow on FrEDI.

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +
add comment here saying that you can also load a different branch or tagged release

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +## Step 2. Use FaIR to create a temperature input for FrEDI (optional)
i'm leaning towards deleting the FaIR part.....i think it takes away from FrEDI.

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +#import the SSP emissions from FaIR repo
if we do keep this, then lets simplify and only include 1 SSP

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +  # FaIR output from Step 2
let's provide 1 output for this Rmd

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +  # csv file with time series of temperature relative to 1995 (units: degC)
relative to 1986-2005

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +  #   (values: >=0 and <= 10)
values can be greater than 10. i would just specify that temps have to be >0

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +#define aggregate categories
sample sector aggregations similar to Hartin et al., 2023

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +#Define color palette
delete color palette

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +#### Plot Temperature Trajectory
i'd be inclined to leave out. users can plot up own temps

2023-03-16 16:48 UTC, cahartin commented on examples/basic_run_example.Rmd
> +table1 <- output_df %>%
is table1 the same as df_filter? if so, let's simplify and call df_filter

2023-03-22 20:20 UTC, emcduffie reviewed
@cahartin - I addressed the issues we discussed today. Take a look at the new FrEDI_run_example.Rmd

2023-06-07 17:57 UTC, cahartin commented
@emcduffie do we still want this if we are setting up a pages instead?

2023-06-08 14:56 UTC, emcduffie commented
We might. I need to play around with pages a little more to figure out what makes the most sense.

2023-06-21 16:46 UTC, closed without merging