New labor
USEPA/FrEDI pull request #7
Opened 2022-02-17 20:01 UTC by knoiva-indecon

Updated package tar.gz file since previous build had a small issue.

2022-02-22 20:40 UTC, cahartin requested changes
@knoiva-indecon a few minor comments.
Also can we update this 2.2.0?

2022-02-22 20:40 UTC, cahartin commented on FrEDI/DESCRIPTION
> +Version: 2.1.1
@knoiva-indecon let's make this 2.2.0

2022-02-22 20:40 UTC, cahartin commented on FrEDI/R/aggregate_impacts.R
> +  return_names  <- df_return %>% names #; "got here9" %>% print
@knoiva-indecon  is this a comment?

2022-02-22 20:40 UTC, cahartin commented on FrEDI/install/00_install.R
> +packageFile_name   <- "FrEDI_2.1.1.tar.gz"
update to 2.2.0

2022-02-22 23:57 UTC, knoiva-indecon commented on FrEDI/install/00_install.R
> +packageFile_name   <- "FrEDI_2.1.1.tar.gz"
Resolved in new push

2022-02-23 00:00 UTC, knoiva-indecon commented on FrEDI/R/aggregate_impacts.R
> +  return_names  <- df_return %>% names #; "got here9" %>% print
Resolved in new push

2022-02-23 00:00 UTC, knoiva-indecon commented on FrEDI/DESCRIPTION
> +Version: 2.1.1
Updated in new push

2022-02-23 00:03 UTC, merged