New sectors merge
USEPA/FrEDI pull request #77
Opened 2023-06-27 17:05 UTC by knoiva-indecon

Ready for a new release. Do to conflicts with the configuration data, may need to recompile FrEDI data after the merge (this issue should be fixed by new approach to data management)

2023-06-29 20:39 UTC, emcduffie requested changes
Just a few minor comments in my review. I was able to install and run the new_sectors branch, so the functionality looks good (including being able to run run_fredi_sv())

You might notice a few recent commits from me related to the DESCRIPTION file. These were updates I needed to make for the io site and then I had to edit again today to make the new edits work with devtools in R. 

Great work!

2023-06-29 20:39 UTC, emcduffie commented on FrEDI/DESCRIPTION
> +Version: 3.4
Curious - do we have a version number protocol that we're following? e.g., do sector additions constitute a X.X number change and then other smaller updates constitute an X.X.X number change? We could add a summary of our versioning protocol to our io page.

2023-06-29 20:39 UTC, emcduffie commented on FrEDI/R/run_fredi.R
> +#' @param outputList A ` TRUE/FALSE` value indicating whether to results as a data frame object (`outputList=FALSE`, default) or to return a list of objects (`outputList=TRUE`) that includes informat
missing word:  '...value indicating whether to [output] results as a data frame object...'

2023-06-29 20:39 UTC, emcduffie commented on FrEDI/R/run_fredi.R
> +    outputList = FALSE, ### Whether to return input arguments as well as results. Returns a list instead of a data frame
Edit: 'outputList = FALSE, ### Whether to return input arguments as well as results. [If TRUE], returns a list instead of a data frame

2023-06-29 20:39 UTC, emcduffie commented on FrEDI/man/import_inputs.Rd
> +\item{popfile}{A character string indicating the location of a CSV file containing a custom population scenario for NCA regions. The first column contains years in the interval 2010 to 2300. The numb
Just want to confirm. The temperature input must start in year 2000 or earlier, but the Pop and GDP inputs only need to start in 2010 or earlier?

2023-06-29 20:39 UTC, emcduffie commented on FrEDI/man/import_inputs.Rd
> +\item{gdpfile}{A character string indicating the location of a CSV file containing a custom scenario for gross domestic product (GDP) (first column contains years; second column contains values for G
Same comment as for Pop.

2023-06-29 20:39 UTC, emcduffie commented on FrEDI/man/run_fredi.Rd
> +\item{outputList}{A \code{ TRUE/FALSE} value indicating whether to results as a data frame object (\code{outputList=FALSE}, default) or to return a list of objects (\code{outputList=TRUE}) that inclu
Missing word: '...value indicating whether to [output] results as a data frame...'

2023-06-29 20:39 UTC, emcduffie commented on FrEDI/man/run_fredi.Rd
> +\item{elasticity=NULL}{A numeric value indicating an elasticity to use for adjusting VSL for applicable sectors and impacts. Applicable sectors and impacts are Air Quality (all impact types), CIL Ext
Please update this note. Elasticities are *not* sector specific.

2023-06-29 20:39 UTC, emcduffie commented on createSystemData/1_configure_FrEDI_main.Rmd
> +mostRecentDate <- "20230503"
Not a big deal, but is it possible to automate this? e.g., reference the date the file was last saved or something like this?

2023-06-29 20:39 UTC, emcduffie commented on FrEDI/R/run_fredi.R
> +#' @param outputList A ` TRUE/FALSE` value indicating whether to results as a data frame object (`outputList=FALSE`, default) or to return a list of objects (`outputList=TRUE`) that includes informat
Also, I didn't know you had added this feature --I really like it!!

It would be good to confirm though that the arguments list always includes all of the input parameters. For example, I was running some tests with this branch and noticed that elasticity is reported in the arguments list if outputList = TRUE in the case where I set the elasticity input, but when I just ran run_fredi(outputList =TRUE), the  arguments list did not include the elasticity value.

2023-06-29 20:48 UTC, knoiva-indecon reviewed
This is a minor change to correct the tool version number. I have reviewed it and it passes my inspection!

2023-06-30 00:19 UTC, knoiva-indecon commented on FrEDI/R/run_fredi.R
> +#' @param outputList A ` TRUE/FALSE` value indicating whether to results as a data frame object (`outputList=FALSE`, default) or to return a list of objects (`outputList=TRUE`) that includes informat
Good catch, added the word "output" in recent pushes. I changed the default elasticity in the function from NULL to 0.4 (it was effectively 0.4 but now it will always show up in the arguments list)

2023-06-30 00:20 UTC, knoiva-indecon commented on FrEDI/R/run_fredi.R
> +    outputList = FALSE, ### Whether to return input arguments as well as results. Returns a list instead of a data frame
Edited comment, although this only appears when you look at the source code

2023-06-30 00:20 UTC, knoiva-indecon commented on FrEDI/man/import_inputs.Rd
> +\item{popfile}{A character string indicating the location of a CSV file containing a custom population scenario for NCA regions. The first column contains years in the interval 2010 to 2300. The numb
That's correct

2023-06-30 00:20 UTC, knoiva-indecon commented on FrEDI/man/import_inputs.Rd
> +\item{gdpfile}{A character string indicating the location of a CSV file containing a custom scenario for gross domestic product (GDP) (first column contains years; second column contains values for G
Correct. This is because the SLR methods are pegged to 2000 and so temperature and SLR must start before that year

2023-06-30 00:21 UTC, knoiva-indecon commented on FrEDI/man/run_fredi.Rd
> +\item{outputList}{A \code{ TRUE/FALSE} value indicating whether to results as a data frame object (\code{outputList=FALSE}, default) or to return a list of objects (\code{outputList=TRUE}) that inclu
Edited documentation in run_fredi.R and then updated documentation, so it should now reflect this change

2023-06-30 00:22 UTC, knoiva-indecon commented on FrEDI/man/run_fredi.Rd
> +\item{elasticity=NULL}{A numeric value indicating an elasticity to use for adjusting VSL for applicable sectors and impacts. Applicable sectors and impacts are Air Quality (all impact types), CIL Ext
I guess the documentation for FrEDI didn't get updated properly or was written over in a merge. It seems fine now, after updating documentation

2023-06-30 00:23 UTC, knoiva-indecon commented on createSystemData/1_configure_FrEDI_main.Rmd
> +mostRecentDate <- "20230503"
It could be automated in theory, but we don't always want to use the most recent file. In any case, we are revising the data process and this will not be an issue once we get that set up

2023-07-12 19:55 UTC, cahartin approved these changes

2023-07-12 19:57 UTC, merged